development:
  clients:
    default:
      database: csvlint_development
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: csvlint_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      uri: <%= ENV['CSVLINT_MONGODB_URL'] || ENV['MONGODB_URI']%>
      options:
        ssl: true